#!/usr/bin/env bash

## Variables

DEVCONTAINER_CONFIG="${DEVCONTAINER_CONFIG:=.devcontainer/devcontainer.json}"

declare -a PORTS


## Functions

usage()
{
    local command
    command="$(basename "$0" | sed 's/-/ /')"
    cat <<EOF
Usage: $command <up|down>

    $command up    # starts proxy for each port in forwardPorts
    $command down  # stops all proxy containers

EOF

    exit 1
}


read_ports_from_config()
{
    IFS=", " read -r -a PORTS <<< \
        "$(grep -E 'forwardPorts.:' "$DEVCONTAINER_CONFIG" | \
            sed 's/.*\[//; s/\].*//; s/"//g; s/,$//')"
}


read_config_property()
{
    local property
    property="$1"
    grep -E "$property.:" "$DEVCONTAINER_CONFIG" | \
        sed 's/.*: //; s/"//g; s/,$//'
}


start_proxy()
{
    local host_and_port="$1"
    echo "$host_and_port"
}


stop_proxy()
{
    echo TODO: stop_proxy "$@"
}


## Main program

COMMAND="$1"
shift
[ -z "$COMMAND" ] && usage

set -euo pipefail

case "$COMMAND" in
    down)
        read_ports_from_config
        echo "${PORTS[@]}"
        ;;
    up)
        read_ports_from_config
        PROJECT="$(read_config_property name)"
        NETWORK="default_$PROJECT"
        for PORT in "${PORTS[@]}"; do
            if [[ $PORT == *:* ]]; then
                SERVICE=${PORT%:*}
                PORT=${PORT#*:}
            else
                SERVICE="$(read_config_property service)"
            fi
            CONTAINER="$PROJECT-$SERVICE-1"
            echo "$CONTAINER on $NETWORK needs port $PORT"
        done
        ;;
    *)
        usage
        ;;
esac
